apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendpy
  namespace: fast-api
  labels:
    apipy: crm
spec:
  replicas: 2
  selector:
    matchLabels:
      apipy: crm
  template:
    metadata:
      labels:
        apipy: crm
    spec:
      containers:
      - name: backend-fast-api
        image: javierllinares/fast-api-tarea:1.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-crm
  namespace: fast-api
spec:
  selector:
    apipy: crm
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8888